# Site
title: natpass
description: natpass主机管理工具
# baseurl: /
permalink: /:title

# Repository
git:
  repository_url: https://github.com/jkstack/natpass

# Navigation
nav:
  deploy:
    - text: 快速部署
      url: /
      available: true
  code:
    - text: S1-代码结构
      url: /step1
      available: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
# exclude: ["README.md"]
