# Site
title: natpass
description: natpass主机管理工具
# baseurl: /
permalink: /:title

# Repository
git:
  repository_url: https://github.com/jkstack/natpass

# Navigation
nav:
  deploy:
    - text: 快速部署
      url: /
      available: true
  code:
    - text: S1-代码结构
      url: /step1
      available: true
    - text: S2-通信协议
      url: /step2
      available: true
    - text: S3-连接池
      url: /step3
      available: true
    - text: S4-shell
      url: /step4
      available: true
    - text: S5-vnc原理
      url: /step5
      available: true
    - text: S6-vnc实现
      url: /step6
      available: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
# exclude: ["README.md"]
